import type { Component } from 'vue'
import {
  ArrowBack,
  ArrowForward,
  Book,
  Boat,
  Brush,
  Bulb,
  ChatbubbleEllipses,
  Checkmark,
  CheckmarkCircle,
  CheckmarkDoneCircle,
  CloseCircle,
  Code,
  ColorPalette,
  Construct,
  Copy,
  Create,
  Cube,
  Document,
  DocumentText,
  Documents,
  Eye,
  FileTrayStacked,
  Flag,
  FolderOpen,
  GitNetwork,
  Grid,
  Hammer,
  HandRight,
  HardwareChip,
  HelpCircle,
  Home,
  InformationCircle,
  Key,
  Layers,
  Link,
  List,
  Locate,
  Menu,
  Navigate,
  Options,
  Person,
  Pricetag,
  RadioButtonOn,
  Reader,
  Refresh,
  Rocket,
  Scan,
  Search,
  Server,
  Settings,
  Share,
  StatsChart,
  Sync,
  Terminal,
  Ticket,
  Time,
  Timer,
  Trash,
  Trophy,
  Videocam,
  Warning
} from '@vicons/ionicons5'

export const iconAliases: Record<string, Component> = {
  Aim: Scan,
  ArrowLeft: ArrowBack,
  ArrowRight: ArrowForward,
  Box: Cube,
  Brush,
  ChatLineRound: ChatbubbleEllipses,
  Checked: Checkmark,
  CircleCheck: CheckmarkCircle,
  CircleCheckFilled: CheckmarkCircle,
  CircleCloseFilled: CloseCircle,
  Connection: GitNetwork,
  CopyDocument: Copy,
  Cpu: HardwareChip,
  DataLine: StatsChart,
  Database: Server,
  Delete: Trash,
  Document,
  DocumentChecked: DocumentText,
  Edit: Create,
  Files: Documents,
  Flag,
  FolderOpened: FolderOpen,
  Goal: RadioButtonOn,
  Grid,
  Guide: Navigate,
  HomeFilled: Home,
  InfoFilled: InformationCircle,
  Key,
  Link,
  List,
  MagicStick: Bulb,
  Monitor: Terminal,
  Mouse: HandRight,
  Operation: Options,
  Picture: FileTrayStacked,
  PriceTag: Pricetag,
  QuestionFilled: HelpCircle,
  Reading: Book,
  Refresh,
  RefreshLeft: Refresh,
  RefreshRight: Sync,
  Right: ArrowForward,
  Rocket,
  Search,
  Select: CheckmarkDoneCircle,
  Server,
  Setting: Settings,
  SetUp: Construct,
  Share,
  Ship: Boat,
  Sort: Layers,
  TableCells: Grid,
  Tickets: Ticket,
  Timer,
  Tools: Hammer,
  TrendCharts: StatsChart,
  Trophy,
  User: Person,
  VideoPlay: Videocam,
  View: Eye,
  WarningFilled: Warning
}
