import type { Component } from 'vue'
import {
  ArrowBack,
  ArrowForward,
  Cube,
  Eye,
  Flag,
  GitNetwork,
  Grid,
  HardwareChip,
  Key,
  Layers,
  Link,
  List,
  LogoJavascript,
  Person,
  Pricetag,
  Refresh,
  Server,
  Share,
  StatsChart,
  Sync,
  Terminal,
  Timer,
  Trash
} from '@vicons/ionicons5'

export const iconAliases: Record<string, Component> = {
  ArrowLeft: ArrowBack,
  ArrowRight: ArrowForward,
  Box: Cube,
  Connection: GitNetwork,
  Cpu: HardwareChip,
  DataLine: StatsChart,
  Database: Server,
  Delete: Trash,
  Flag,
  JavaScriptIcon: LogoJavascript,
  Key,
  Link,
  List,
  Monitor: Terminal,
  PriceTag: Pricetag,
  Refresh,
  RefreshRight: Sync,
  Server,
  Share,
  Sort: Layers,
  TableCells: Grid,
  Timer,
  User: Person,
  View: Eye
}
